version: '1'
services:
  nextjs:
    container_name: nextjs-arista
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: on-failure
