export type TDataAll = {
    id: number;
    hostname?: string;
    ethernet_ip: string;
    client_port: number;
    client_username: string;
    client_password: string;
    client_lab: string;
    traffic_profile: string;
    description: string;
    interface_name: string;
    ssid_name: string | null;
    bssid: string | null;
    hwaddr: string | null;
    rssi: number | null;
    txpower: number | null;
    channel: number | null;
    channel_width: string | null;
    channel_band: string | null;
    security: string | null;
    phymode: string | null;
    phyrate: number | null;
    noise_measurement: number | null;
    wifi_status: string;
    ethernet_status: boolean;
    created_at : string;
    updated_at : string;
    user: number;
};

export type TClient = {
    hostname?:string;
    id: number;
    ethernet_ip: string;
    client_port: number;
    client_username: string;
    client_password: string;
    client_lab: string;
    traffic_profile: string;
    description: string;
    interface_name: string;
    ssid_name: string | null;
    bssid: string | null;
    hwaddr: string | null;
    rssi: number | null;
    txpower: number | null;
    channel: number | null;
    channel_width: string | null;
    channel_band: string | null;
    security: string | null;
    phymode: string | null;
    phyrate: number | null;
    noise_measurement: number | null;
    wifi_status: string;
    ethernet_status: boolean;
}