import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { Toaster } from "@/components/ui/toaster"
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
import Image from "next/image"
import { SidebarNav } from "@/components/ui/sidebar-nav"
import { Separator } from "@/components/ui/separator"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarNavItems = [
  {
    title: "Dashboard",
    href: "/",
  },
  {
    title: "Traffic Profile",
    href: "/traffic",
  },
  {
    title: "Configure SSID",
    href: "/ssid",
  },
  {
    title: "Settings",
    href: "/settings",
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning={true}
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          fontSans.variable
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <>
            <div className="md:hidden ">
            </div>
            <div className="hidden space-y-6 p-10 pb-16 md:block overflow-hidden ">
              <div className="space-y-0.5">
                <h2 className="text-2xl font-bold tracking-tight">Client Management System</h2>
                <p className="text-muted-foreground">
                  Manage your clients and run real-time traffic.
                </p>
              </div>
              <Separator className="my-6" />
              <div className="flex flex-col space-y-8 lg:flex-row w-screen lg:space-y-0">
                <aside className="-mx-4 w-max mr-10">
                  <SidebarNav items={sidebarNavItems} />
                </aside>
                <div className="flex-1 w-screen mr-20 ">{children}</div>
              </div>
            </div>
          </>


          {/* {children} */}
          {/* <Toaster richColors position="top-center" /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}

// interface SettingsLayoutProps {
//   children: React.ReactNode
// }

// export default function SettingsLayout({ children }: SettingsLayoutProps) {
//   return (
//     <>
//       <div className="md:hidden">
//         <Image
//           src="/examples/forms-light.png"
//           width={1280}
//           height={791}
//           alt="Forms"
//           className="block dark:hidden"
//         />
//         <Image
//           src="/examples/forms-dark.png"
//           width={1280}
//           height={791}
//           alt="Forms"
//           className="hidden dark:block"
//         />
//       </div>
//       <div className="hidden space-y-6 p-10 pb-16 md:block">
//         <div className="space-y-0.5">
//           <h2 className="text-2xl font-bold tracking-tight">Settings</h2>
//           <p className="text-muted-foreground">
//             Manage your account settings and set e-mail preferences.
//           </p>
//         </div>
//         <Separator className="my-6" />
//         <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
//           <aside className="-mx-4 lg:w-1/5">
//             <SidebarNav items={sidebarNavItems} />
//           </aside>
//           <div className="flex-1 lg:max-w-2xl">{children}</div>
//         </div>
//       </div>
//     </>
//   )
// }
