
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { Toaster } from "@/components/ui/toaster"
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
import Image from "next/image"
import { SidebarNav } from "@/components/ui/sidebar-nav"
import { Separator } from "@/components/ui/separator"
import { LogoutComp } from "@/components/custom/auth/logout"
import { logout } from "@/actions/auth/loginActions";


export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const sidebarNavItems = [
  {
    title: "Dashboard",
    href: "/dashboard",
  },
  {
    title: "Traffic Profile",
    href: "/traffic",
  },
  {
    title: "SSID",
    href: "/ssid",
  },
  {
    title: "Settings",
    href: "/settings",
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div>
          <div className="md:hidden ">
          </div>
          <div className="hidden space-y-6 p-10 pb-16 md:block overflow-hidden ">
            <div className="space-y-0.5">
              <div className="flex items-center justify-between">
                
              <h2 className="text-2xl font-bold tracking-tight">Client Management System</h2>
              <LogoutComp logout={logout} />
              </div>
              <p className="text-muted-foreground">
                Manage your clients and run real-time traffic.
              </p>
            </div>
            <Separator className="my-6" />
            <div className="flex flex-col space-y-8 lg:flex-row w-screen lg:space-y-0">
              <aside className="-mx-4 w-max mr-10">
                <SidebarNav items={sidebarNavItems} />
              </aside>
              <div className="flex-1 w-screen mr-20 ">{children}</div>
            </div>
          </div>
        </div>
  );
}
